name = "ITensorChemistry"
uuid = "cbb729c8-cb01-4982-b6b1-bc32521fc628"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[targets]
test = ["Test"]
